format = """
$character\
$cmd_duration\
$nix_shell\
$python\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status"""

add_newline = false

[directory]
style = "bold black"

[git_branch]
style = "bold cyan"
format = "[$symbol$branch ]($style)"

[git_status]
style = "yellow"
format = "([$modified]($style) )"
modified = "✗"

[nix_shell]
style = "yellow"
format = "[{ $name }]($style) "

[cmd_duration]
format = '\($duration\) '
