#!/bin/bash
# 
# xmonad "startup hook" script. This gets run after xmonad is initialized,
# via the startupHook facility provided by xmonad. It's useful for 
# running any programs which you want to use within xmonad but
# which don't need to be initialized before xmonad is running. 

#
# TRAY ICON SOFTWARE
#

# Network manager, so we don't have to configure wifi at the command line.
if [ -z "$(pgrep nm-applet)" ] ; then
    nm-applet --sm-disable &
fi

# Applet for managing print jobs from the tray.
if [ -z "$(pgrep system-config-printer-applet)" ] ; then
    system-config-printer-applet &
fi

# Sound applet
if [ -x /usr/bin/gnome-sound-applet ] ; then
   sleep 10
   gnome-sound-applet &
fi

# Dropbox
dropbox start &

setxkbmap -option grp:alt_shift_toggle us,de
