# This file contains default non-project-specific settings for 'stack', used
# in all projects.  For more information about stack's configuration, see
# http://docs.haskellstack.org/en/stable/yaml_configuration/
#

templates:
  params:
    author-email: mdrexl@fastmail.fm
    author-name: Moritz Drexl
    github-username: the-moritz

nix:
  enable: true
  packages:
    - gcc
    - git
    - ncurses.out
    - ncurses.dev
    - zlib.out
    - zlib.dev
    - gmp.out
    - gmp.dev
